Vagrant.configure("2") do |config|
  config.vm.define "hqsdfgh" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "hqsdfgh"
    machine.vm.network "private_network", ip: "192.168.56.22"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "hqsdfgh"
      vb.customize ["modifyvm", :id, "--name", "hqsdfgh"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "nbvcxwxcvbn" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "nbvcxwxcvbn"
    machine.vm.network "private_network", ip: "192.168.56.21"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "nbvcxwxcvbn"
      vb.customize ["modifyvm", :id, "--name", "nbvcxwxcvbn"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
