Vagrant.configure("2") do |config|
  config.vm.define "trn" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "trn"
    machine.vm.network "private_network", ip: "192.168.56.79"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "trn"
      vb.customize ["modifyvm", :id, "--name", "trn"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "fre" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "fre"
    machine.vm.network "private_network", ip: "192.168.56.78"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "fre"
      vb.customize ["modifyvm", :id, "--name", "fre"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
