Vagrant.configure("2") do |config|
  config.vm.define "xsq" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "xsq"
    machine.vm.network "private_network", ip: "xsxsx"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "xsq"
      vb.customize ["modifyvm", :id, "--name", "xsq"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "xsqx" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "xsqx"
    machine.vm.network "private_network", ip: "xsq"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "xsqx"
      vb.customize ["modifyvm", :id, "--name", "xsqx"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "xsq" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "xsq"
    machine.vm.network "private_network", ip: "xsq"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "xsq"
      vb.customize ["modifyvm", :id, "--name", "xsq"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
