Vagrant.configure("2") do |config|
  config.vm.define "sdfghj" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "sdfghj"
    machine.vm.network "private_network", ip: "192.168.56.24"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "sdfghj"
      vb.customize ["modifyvm", :id, "--name", "sdfghj"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "wxcvbn" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "wxcvbn"
    machine.vm.network "private_network", ip: "192.168.56.25"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "wxcvbn"
      vb.customize ["modifyvm", :id, "--name", "wxcvbn"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
