Vagrant.configure("2") do |config|
  config.vm.define "hj" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "hj"
    machine.vm.network "private_network", ip: "192.168.56.45"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "hj"
      vb.customize ["modifyvm", :id, "--name", "hj"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "jh" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "jh"
    machine.vm.network "private_network", ip: "192.168.56.48"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "jh"
      vb.customize ["modifyvm", :id, "--name", "jh"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
