Vagrant.configure("2") do |config|
  config.vm.define "nnnode" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "nnnode"
    machine.vm.network "private_network", ip: "192.168.56.47"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "nnnode"
      vb.customize ["modifyvm", :id, "--name", "nnnode"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "ddnode" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "ddnode"
    machine.vm.network "private_network", ip: "192.168.56.49"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "ddnode"
      vb.customize ["modifyvm", :id, "--name", "ddnode"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
