Vagrant.configure("2") do |config|
  config.vm.define "dffg" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "dffg"
    machine.vm.network "private_network", ip: "192.168.56.25"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "dffg"
      vb.customize ["modifyvm", :id, "--name", "dffg"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "jgfdfds" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "jgfdfds"
    machine.vm.network "private_network", ip: "192.168.56.28"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "jgfdfds"
      vb.customize ["modifyvm", :id, "--name", "jgfdfds"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
