Vagrant.configure("2") do |config|
  config.vm.define "bnhhh" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "bnhhh"
    machine.vm.network "private_network", ip: "192.168.56.46"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "bnhhh"
      vb.customize ["modifyvm", :id, "--name", "bnhhh"]
      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "datanidoe" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "datanidoe"
    machine.vm.network "private_network", ip: "192.168.56.48"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "datanidoe"
      vb.customize ["modifyvm", :id, "--name", "datanidoe"]
      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
