Vagrant.configure("2") do |config|
  config.vm.define "yetetetetet" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "yetetetetet"
    machine.vm.network "private_network", ip: "cds"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "yetetetetet"
      vb.customize ["modifyvm", :id, "--name", "yetetetetet"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "cdns" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "cdns"
    machine.vm.network "private_network", ip: "dcsm"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "cdns"
      vb.customize ["modifyvm", :id, "--name", "cdns"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "mfdm" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "mfdm"
    machine.vm.network "private_network", ip: "cxds"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "mfdm"
      vb.customize ["modifyvm", :id, "--name", "mfdm"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
