Vagrant.configure("2") do |config|
  config.vm.define "cds" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "cds"
    machine.vm.network "private_network", ip: "cds"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "cds"
      vb.customize ["modifyvm", :id, "--name", "cds"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "cs" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "cs"
    machine.vm.network "private_network", ip: "cds"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "cs"
      vb.customize ["modifyvm", :id, "--name", "cs"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "csc" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "csc"
    machine.vm.network "private_network", ip: "cds"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "csc"
      vb.customize ["modifyvm", :id, "--name", "csc"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
