Vagrant.configure("2") do |config|
  config.vm.define "nmnode" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "nmnode"
    machine.vm.network "private_network", ip: "192.168.56.41"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "nmnode"
      vb.customize ["modifyvm", :id, "--name", "nmnode"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "dacd" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "dacd"
    machine.vm.network "private_network", ip: "192.168.56.42"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "dacd"
      vb.customize ["modifyvm", :id, "--name", "dacd"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
