Vagrant.configure("2") do |config|
  config.vm.define "bnk" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "bnk"
    machine.vm.network "private_network", ip: "192.168.56.23"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "bnk"
      vb.customize ["modifyvm", :id, "--name", "bnk"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "klm" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "klm"
    machine.vm.network "private_network", ip: "192.168.56.25"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "klm"
      vb.customize ["modifyvm", :id, "--name", "klm"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
