---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Java (OpenJDK 8)
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Configure /etc/hosts from template
      template:
        src: ../templates/hosts.j2
        dest: /etc/hosts
