---
- hosts: all
  become: yes
  vars:
    HADOOP_HOME: /opt/hadoop
    JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
  tasks:
    - name: Set Hadoop environment variables
      copy:
        dest: /etc/profile.d/hadoop.sh
        content: |
          export HADOOP_HOME={{ HADOOP_HOME }}
          export JAVA_HOME={{ JAVA_HOME }}
      mode: '0755'
