---
- hosts: namenode
  become: yes
  vars:
    hadoop_version: "3.3.1"
  tasks:
    - name: Format HDFS if not already formatted
      command: "/opt/hadoop-{{ hadoop_version }}/bin/hdfs namenode -format"
      args:
        creates: "/opt/hadoop-{{ hadoop_version }}/dfs/name/current/VERSION"
    - name: Start HDFS
      command: "/opt/hadoop-{{ hadoop_version }}/sbin/start-dfs.sh"

- hosts: resourcemanager
  become: yes
  vars:
    hadoop_version: "3.3.1"
  tasks:
    - name: Start YARN
      command: "/opt/hadoop-{{ hadoop_version }}/sbin/start-yarn.sh"
