Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "test11"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "test11"
    vb.memory = "2048"
    vb.cpus = 1
  end
end
