---
- hosts: namenode
  become: yes
  vars:
    hadoop_version: "3.3.1"
    replication_factor: 3
    hadoop_tmp_dir: /opt/hadoop-{{ hadoop_version }}/tmp
    fs_default_name: "hdfs://{{ inventory_hostname }}:9000"
  tasks:
    - name: Deploy core-site.xml
      template:
        src: ../templates/core-site.xml.j2
        dest: /opt/hadoop-{{ hadoop_version }}/etc/hadoop/core-site.xml
    - name: Deploy hdfs-site.xml
      template:
        src: ../templates/hdfs-site.xml.j2
        dest: /opt/hadoop-{{ hadoop_version }}/etc/hadoop/hdfs-site.xml

- hosts: resourcemanager
  become: yes
  vars:
    hadoop_version: "3.3.1"
  tasks:
    - name: Deploy yarn-site.xml
      template:
        src: ../templates/yarn-site.xml.j2
        dest: /opt/hadoop-{{ hadoop_version }}/etc/hadoop/yarn-site.xml
    - name: Deploy mapred-site.xml
      template:
        src: ../templates/mapred-site.xml.j2
        dest: /opt/hadoop-{{ hadoop_version }}/etc/hadoop/mapred-site.xml
