Vagrant.configure("2") do |config|
  config.vm.define "zetyui" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "zetyui"
    machine.vm.network "private_network", ip: "192.168.56.24"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "zetyui"
      vb.customize ["modifyvm", :id, "--name", "zetyui"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "azertyui" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "azertyui"
    machine.vm.network "private_network", ip: "192.168.56.25"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "azertyui"
      vb.customize ["modifyvm", :id, "--name", "azertyui"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
