Vagrant.configure("2") do |config|
  config.vm.define "ddddddd" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "ddddddd"
    machine.vm.network "private_network", ip: "192.168.56.10"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "ddddddd"
      vb.customize ["modifyvm", :id, "--name", "ddddddd"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "vcv" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "vcv"
    machine.vm.network "private_network", ip: "192.168.56.12"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "vcv"
      vb.customize ["modifyvm", :id, "--name", "vcv"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
