Vagrant.configure("2") do |config|
  config.vm.define "sdsd" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "sdsd"
    machine.vm.network "private_network", ip: "192.168.56.21"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "sdsd"
      vb.customize ["modifyvm", :id, "--name", "sdsd"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "hjhjjh" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "hjhjjh"
    machine.vm.network "private_network", ip: "192.168.56.23"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "hjhjjh"
      vb.customize ["modifyvm", :id, "--name", "hjhjjh"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
