Vagrant.configure("2") do |config|
  config.vm.define "klds" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "klds"
    machine.vm.network "private_network", ip: "dss"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "klds"
      vb.customize ["modifyvm", :id, "--name", "klds"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = ""
    machine.vm.network "private_network", ip: ""
    machine.vm.provider "virtualbox" do |vb|
      vb.name = ""
      vb.customize ["modifyvm", :id, "--name", ""]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = ""
    machine.vm.network "private_network", ip: ""
    machine.vm.provider "virtualbox" do |vb|
      vb.name = ""
      vb.customize ["modifyvm", :id, "--name", ""]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
