Vagrant.configure("2") do |config|
  config.vm.define "c" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "c"
    machine.vm.network "private_network", ip: "192.168.0.123"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "c"
      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
