Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "VMTest"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "VMTest"
    vb.memory = "2048"
    vb.cpus = 2
  end
end
