Vagrant.configure("2") do |config|
  config.vm.define "cd" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "cd"
    machine.vm.network "private_network", ip: "cd"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "cd"
      vb.customize ["modifyvm", :id, "--name", "cd"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "cd" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "cd"
    machine.vm.network "private_network", ip: "e"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "cd"
      vb.customize ["modifyvm", :id, "--name", "cd"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "cd" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "cd"
    machine.vm.network "private_network", ip: "cd"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "cd"
      vb.customize ["modifyvm", :id, "--name", "cd"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
