Vagrant.configure("2") do |config|
  config.vm.define "nnnn" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "nnnn"
    machine.vm.network "private_network", ip: "192.168.0.126"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "nnnn"
      vb.customize ["modifyvm", :id, "--name", "nnnn"]
      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "jkk" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "jkk"
    machine.vm.network "private_network", ip: "192.1668.0.45"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "jkk"
      vb.customize ["modifyvm", :id, "--name", "jkk"]
      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
