---
- name: Démarrer les services Hadoop
  hosts: namenode
  become: yes
  tasks:
    - name: Formater le NameNode (si nécessaire)
      command: /opt/hadoop/bin/hdfs namenode -format -force
      args:
        creates: /opt/hadoop/hdfs/name/current/VERSION

    - name: Démarrer HDFS
      command: /opt/hadoop/sbin/start-dfs.sh

    - name: Démarrer YARN
      command: /opt/hadoop/sbin/start-yarn.sh
