Vagrant.configure("2") do |config|
  config.vm.define "qq" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "qq"
    machine.vm.network "private_network", ip: "192.168.56.107"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "qq"
      vb.customize ["modifyvm", :id, "--name", "qq"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "gfd" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "gfd"
    machine.vm.network "private_network", ip: "192.168.56.106"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "gfd"
      vb.customize ["modifyvm", :id, "--name", "gfd"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
