Vagrant.configure("2") do |config|
  config.vm.define "nki" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "nki"
    machine.vm.network "private_network", ip: "192.168.56.73"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "nki"
      vb.customize ["modifyvm", :id, "--name", "nki"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "ndi" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "ndi"
    machine.vm.network "private_network", ip: "192.168.56.79"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "ndi"
      vb.customize ["modifyvm", :id, "--name", "ndi"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
