Vagrant.configure("2") do |config|
  config.vm.define "nnnn" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "nnnn"
    machine.vm.network "private_network", ip: "192.168.56.36"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "nnnn"
      vb.customize ["modifyvm", :id, "--name", "nnnn"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
  config.vm.define "ddddddddd" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "ddddddddd"
    machine.vm.network "private_network", ip: "192.168.56.34"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "ddddddddd"
      vb.customize ["modifyvm", :id, "--name", "ddddddddd"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
