---
- name: Démarrer les services Hadoop
  hosts: namenode
  become: yes
  tasks:
    - name: Mettre à jour hadoop-env.sh pour définir JAVA_HOME
      shell: |
        if grep -q '^export JAVA_HOME=' /opt/hadoop/etc/hadoop/hadoop-env.sh; then
          sed -i 's|^export JAVA_HOME=.*|export JAVA_HOME=/usr/lib/jvm/default-java|' /opt/hadoop/etc/hadoop/hadoop-env.sh;
        else
          echo 'export JAVA_HOME=/usr/lib/jvm/default-java' >> /opt/hadoop/etc/hadoop/hadoop-env.sh;
        fi
      args:
        executable: /bin/bash

    - name: Créer le répertoire /opt/hadoop/logs si nécessaire
      file:
        path: /opt/hadoop/logs
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Formater le NameNode (si nécessaire)
      shell: "/opt/hadoop/bin/hdfs namenode -format -force"
      args:
        creates: /opt/hadoop/hdfs/name/current/VERSION
      become_user: vagrant
      environment:
        JAVA_HOME: /usr/lib/jvm/default-java
      executable: /bin/bash

    - name: Démarrer HDFS
      shell: "/opt/hadoop/sbin/start-dfs.sh"
      become_user: vagrant
      environment:
        JAVA_HOME: /usr/lib/jvm/default-java
        HDFS_NAMENODE_USER: vagrant
        HDFS_DATANODE_USER: vagrant
        HDFS_SECONDARYNAMENODE_USER: vagrant
      executable: /bin/bash

    - name: Démarrer YARN
      shell: "/opt/hadoop/sbin/start-yarn.sh"
      become_user: vagrant
      environment:
        JAVA_HOME: /usr/lib/jvm/default-java
      executable: /bin/bash
