Vagrant.configure("2") do |config|
  config.vm.define "jklk" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "jklk"
    machine.vm.network "private_network", ip: "192.168.56.30"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "jklk"
      vb.customize ["modifyvm", :id, "--name", "jklk"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
